---
title: "align_output"
author: "Griffin Tibbitts"
date: '2023-05-31'
output: html_document
---

```{r}
rm(list=ls())
```
```{r}
library(dplyr)
library(tidyr)
```

```{r}
info <- list.files('/work/larylab/dbgap/data3/phg000835.v5.FHS_SHARE_imputed_HRC1.marker-info.MULTI')
```
```{r}

```
```{r}
sample <- read.table('/work/larylab/dbgap/data3/phg000835.v5.FHS_SHARE_imputed_HRC1.marker-info.MULTI/chr1.info', header = T, nrows = 100) %>%
  rename(REF = 'REF.0.', ALT = 'ALT.1.') %>%
  separate(SNP, into = c('CHR', 'POS'), sep = ':') %>% 
  mutate(CHR = as.numeric(CHR),
          POS = as.numeric(POS))

sample_assoc <- read.table('/work/larylab/Griffin_Stuff/Haojie_GWAS/results/rvtest_Male/Male.EUR.TBS.MetaScore.assoc.gz', header = T, nrows = 100) %>%
  rename(CHR = CHROM)
```
```{r}
sample_merge <- merge(sample, sample_assoc, by = 'key', all.y = T)
```
```{r}
sample$key = paste(sample$CHR, sample$POS, sample$REF, sample$ALT, sep = '_')
length(unique(sample$key))
```
```{r}
sample_assoc$key = paste(sample_assoc$CHR, sample_assoc$POS, sample_assoc$REF, sample_assoc$ALT, sep = '_')
length(unique(sample_assoc$key))
```

```{r}
setwd('/work/larylab/dbgap/data3/phg000835.v5.FHS_SHARE_imputed_HRC1.marker-info.MULTI')
for (file in info){
  if (length(grep('gz', file)) == 0){
    print(file)
    if (exists('exdata')){
      tmpdata <- read.table(file, header = T) %>%
        #filter(MAF > 0.05) %>%
        select(SNP, Rsq, MAF, 'Ref.0.', 'Alt.1.')
      exdata <- rbind(exdata, tmpdata)
    }
    if (!(exists('exdata'))) {
      tmpdata <- read.table(file, header = T) %>%
        #filter(MAF >= 0.05) %>%
        select(SNP, Rsq, MAF, 'Ref.1.', 'Alt.1.')
      exdata <- tmpdata
    }
  }
}
```


```{r}
exdata <- exdata %>%
  separate(SNP, into = c('CHR', 'POS'), sep = ':') %>% 
  mutate(CHR = as.numeric(CHR),
          POS = as.numeric(POS))
```
```{r}
head(exdata)
```


```{r}
assoc <- read.table(gzfile('/work/larylab/Griffin_Stuff/Haojie_GWAS/results/rvtest_Male/Male.EUR.TBS.MetaScore.assoc.gz'), header = T)
assoc <- assoc %>% rename(CHR = colnames(assoc[1]))
```

```{r}
assoc_1 <- merge(assoc, exdata, by = c('CHR','POS'), all.x = T)
```
```{r}
assoc_2 <- assoc_1 %>%
  filter(!is.na(REF))
```

```{r}
#table(assoc$CHR)

#filter(assoc_2, CHR == 1)
#filter(assoc, CHR == 1)

length(df.duplicated())
```

```{r}
setwd('/work/larylab/Griffin_Stuff/Haojie_GWAS/results')
write.table(assoc, gzfile('FRAM_thickness_male_20220613_RVTEST_b37_GS_CWL.gz', 'w'), row.names = F)
```

```{r}
# Now load in the merged files and rename
# This is due to the rename step being dramatically faster 
path <- '/work/larylab/Griffin_Stuff/Haojie_GWAS/results/'
```


```{r}

```


```{r}
head(assoc)
```


```{r}
assoc <- read.table(gzfile(paste0(path, 'FRAM_thickness_male_20220613_RVTEST_b37_GS_CWL.gz')), header = T)
assoc <- assoc %>%
  rename(BP = POS,
         EA = REF,
         NEA = ALT,
         EAF = AF,
         INFO = Rsq,
         BETA = ALT_EFFSIZE,
         SE = SQRT_V_STAT,
         P = PVALUE,
         N = N_INFORMATIVE)
assoc <- assoc %>%
  select(CHR,
         BP,
         EA,
         NEA,
         EAF,
         INFO,
         BETA,
         SE,
         P,
         N)
write.table(assoc, (gzfile(paste0(path,
                                  'FHS_thickness_male_20220613_RVTEST_b37_EA_GS.gz'), 'w')))
```

```{r}
assoc <- read.table(gzfile(paste0(path, 'FHS_thickness_female_20220601_RVTEST_b37_EA_GS.gz')), header = T)
```
```{r}
assoc <- assoc %>%
  mutate(SE = 1/SE)
```
```{r}
head(assoc)
```

```{r}
write.table(assoc, (gzfile(paste0(path,
                                  'FHS_thickness_all_20220612_RVTEST_b37_GS_CWL.gz'), 'w')))
```

